version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    ##depends_on: servia para esperar a inicialização de um serviço antes de iniciar outro, isso na versão 2 do docker-compose
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 ##--innodb-force-recovery=1 
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - node-network

networks:
  node-network:
    driver: bridge ##test
